### ISSUE TITLE
Generate other protobuf files

### ISSUE THREAD

**Issue by sebleclerc** [Egorand/wire-multiplatform-sample#7]
Hey! I checked this sample and wanted to see how our proto files are compiled to Kotlin. When I add them under `protos/src/main/proto/something` and build the whole project, I see under `build/generated` the 2 Kotlin classes for Dinosaurs and Geology but I don't see the ones I added.

Do I have to specify a folder to look to .proto files?

Thanks!

**Comment by Egorand** [comment]
Nope, having them under `src/main/proto` should be enough. Make sure the protos are in the right packages and that you're using `proto2` - Wire doesn't support `proto3` at the moment.

**Comment by sebleclerc** [comment]
Oh! Well that is why. We are using `proto3`. Any aprox. time for proto3 support of Wire?

**Comment by Egorand** [comment]
Wire is an open source library developed entirely on volunteer effort, so we don't normally provide any ETAs. Follow https://github.com/square/wire/issues/279 and feel free to contribute!

**Comment by sebleclerc** [comment]
Sure! I'll have look at the issue. Thanks for the clarifications!
